# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66121b9ba473efdbe78cf93ae1e4dc45"
name = "easy insights basic"
handle = "easy-insights-basic"
application_url = "https://dynamics-aruba-acceptance-members.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "etml-testing.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://dynamics-aruba-acceptance-members.trycloudflare.com/auth/callback",
  "https://dynamics-aruba-acceptance-members.trycloudflare.com/auth/shopify/callback",
  "https://dynamics-aruba-acceptance-members.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
